
# Generated by Django 2.1.5 on 2019-02-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_shs', models.FloatField(blank=True, null=True)),
                ('height_shs', models.FloatField(blank=True, null=True)),
                ('diameter_pipe', models.FloatField(blank=True, null=True)),
                ('wall', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateField()),
                ('act_number', models.SmallIntegerField()),
                ('counterparty', models.TextField()),
                ('length_from', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('length_to', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('wall_thickness_max', models.FloatField()),
                ('wall_thickness_min', models.FloatField()),
                ('radius_rounding_max', models.FloatField()),
                ('radius_rounding_min', models.FloatField()),
                ('pipe_diam_out', models.FloatField()),
                ('pipe_diam_in', models.FloatField()),
                ('uktzed', models.IntegerField()),
                ('price_in', models.FloatField()),
                ('price_in_nds', models.FloatField()),
                ('price_out', models.FloatField()),
                ('price_out_NDS', models.FloatField()),
                ('base_units_weight', models.PositiveSmallIntegerField(choices=[(1, 'tn'), (2, 'm'), (3, 'posluga')])),
                ('base_units_length', models.PositiveSmallIntegerField(choices=[(1, 'tn'), (2, 'm'), (3, 'posluga')])),
                ('weight_acc', models.FloatField()),
                ('weight_fact', models.FloatField()),
                ('stock', models.TextField()),
                ('place', models.TextField()),
                ('contract', models.TextField()),
                ('created_by', models.TextField()),
                ('create_date', models.DateField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SmallIntegerField(choices=[(1, 'GOST 8732'), (2, 'GOST 8734'), (3, 'GOST 10705'), (4, 'GOST 10706'), (5, 'TU UV  2.7 , 2.4.45')])),
                ('steel', models.SmallIntegerField(choices=[(1, 'steel 20'), (2, 'steel 35'), (4, 'steel 09G2S')])),
                ('comment', models.TextField(blank=True, max_length=15, null=True)),
                ('strength_yield', models.SmallIntegerField()),
                ('strength_tensile', models.SmallIntegerField()),
                ('extending', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Standard'),
        ),
    ]
