# Generated by Django 2.1.5 on 2019-02-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.SmallIntegerField(choices=[(1, 'TOV'), (2, 'FOP'), (3, 'PP'), (4, 'ZAT')])),
                ('name', models.CharField(max_length=120)),
                ('inn', models.IntegerField()),
                ('edrpou', models.IntegerField()),
                ('adress_by_documents', models.CharField(max_length=200)),
                ('adress_by_fact', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('create_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('playground', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='counterparty',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='pipe_diam_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='pipe_diam_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Place'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='price_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='price_in_nds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='price_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='price_out_NDS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='radius_rounding_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='radius_rounding_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='stock',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='uktzed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='wall_thickness_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='wall_thickness_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='weight_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='weight_fact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Location'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='from_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Counterparty'),
        ),
    ]
