# Generated by Django 2.1.5 on 2019-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190204_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='product_type',
            field=models.TextField(max_length=20, null=True, unique=True),
        ),
    ]
