# Generated by Django 2.1.5 on 2019-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190204_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diameter_pipe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
